---

# Travis file for Jenkins role

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine'

script:
  - 'pip install tox-travis'

script:
  - 'tox'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
