---

# Tasks file for jenkins

- name: Load the OS specific varibles
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"

- include: install_debian.yml
  tags:
    - install
    - ntp
  when: ansible_os_family == "Debian"

